  
title: Minimal theme
logo: https://avatars3.githubusercontent.com/u/67387645?s=460&u=dc5f082a8c7de18efd97e463b2568f959f0b51ad&v=4
description: Minimal is a theme for GitHub Pages.
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
